# Mengaktifkan library AndroidX (Memperbaiki Error #1 dan #4)
android.useAndroidX=true

# Mengonversi library lama ke AndroidX secara otomatis (Memperbaiki Error #4)
android.enableJetifier=true

# Menambah memori untuk Gradle agar tidak kehabisan (Memperbaiki Error #2)
org.gradle.jvmargs=-Xmx4g